baseURL: "https://linethmamuthukuda.github.io/Linethma-Port/" 
title: Dona Linethma Muthukuda
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: about/
          weight: 1
        - name: Results
          url: results/
          weight: 2
        - name: Location
          url: location/
          weight: 3
        - name: GitHub Files
          url: github/
          weight: 4
        - name: Archive
          url: archive/
          weight: 5

params:
    description: "Personal website and portfolio of Dona Linethma Muthukuda, a Cyber Security Student at the SLT Mobitel Nebula Institute of Technology."
    author: Dona Linethma Muthukuda
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [books, courses, papers, data]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dona Linethma Muthukuda 
          subtitle: "I am a Cyber Security Student at the SLT Mobitel Nebula Institute of Technology"
          imageUrl: picture.jpeg
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: about/
            - name: Results
              url: results/
            - name: Location
              url: location/
            - name: GitHub Files
              url: github/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:linethmamuthukuda123@gmail.com
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/LinethmaMuthukuda

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Dona Linethma Muthukuda
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2